name: Docker Image CI

on:
  push:
    branches: [ master ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build the Docker image
      run: |
        cd $GITHUB_WORKSPACE
        docker --version
        ./utils/setup_emulation
        docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
        ./dockerbuild
        ./dockerpush
        
